### ISSUE TITLE
editor.tabsize and extension tab size not correct

### ISSUE THREAD

**Issue by mderkach** [mblode/vscode-twig-language-2#37]
Hi! Here is my VS Code settings: https://gyazo.com/726cd79d17a82d93ef5975faf4ec7952
But when i use "Format document", extension always сhange tab size to 4:
1)before https://gyazo.com/1cd9d9d1deb178865c55030353a840f5
2)after https://gyazo.com/64de2c3c855e27bf70b6351744201b86

I have tried solutions from another similiar issues, but it takes no effect
Any help?

**Comment by chasegiunta** [comment]
Having this same issue.

**Comment by mblode** [comment]
Thanks @mderkach for bringing this to my attention! I've just pushed a fix and indentation should work properly now 👍

**Comment by versedi** [comment]
Either this bug is back or there's a lack configuration reference in readme.

**Comment by mblode** [comment]
0.12.0 uses the document’s tab size and indentation style. Added tests for spaces, tabs and settings changes.
