### ISSUE TITLE
HTML comments shift

### ISSUE THREAD

**Issue by eytienne** [mblode/vscode-twig-language-2#38]
The extension shifts the html multi-line comments to the right with each save of the file. My vs code is using html (twig) configuration and this indentation bug is pretty annoying.

**Comment by mblode** [comment]
This has been fixed in the latest update 👍

**Comment by montemartin** [comment]
I'm still having this issue. It also happens twig comments as well. See my earlier comment on #56

**Comment by sunscreem** [comment]
I'm also having this issue.

**Comment by eytienne** [comment]
@sunscreem in front of this evil bug, it seems wiser and faster to hand comment your twig

**Comment by kevinmu17** [comment]
Still exists after formatting

**Comment by petehjfd** [comment]
This issue still exists in 0.9.2.

**Comment by mblode** [comment]
Fixed the growing comment indentation in 0.12.0. Regression tests check that repeated formatting stays stable.
